version: "3.8"

services:
  frontend-dev:
    profiles: ["dev"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true

  frontend:
    profiles: ["prod"]
    image: hassenamri005/vanlog:frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    env_file:
      - .env
    stdin_open: true
    tty: true
