version: '3.8'

services:
  postgres:
    image: postgres:13.5
    container_name: vanlog-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: vanlog-backend
    restart: always
    ports:
      - "6001:6001"
    env_file:
      - .env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: vanlog-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: