services:
  postgres:
    image: postgres:13.5
    container_name: sam-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: sam-backend
    restart: always
    ports:
      - "6001:6001"
    env_file:
      - .env
    environment:
     DATABASE_URL: postgresql://postgres:post123@postgres:5432/samlogistic?schema=public
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && node dist/src/main.js"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        VITE_BASE_URL: ${VITE_BASE_URL:-https://api.samlogistic.tn}
    container_name: sam-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
