export const TunCities = [
  { value: "tunis", label: "Tunis" },
  { value: "sfax", label: "Sfax" },
  { value: "sousse", label: "Sousse" },
  { value: "ettadhamen", label: "Ettadhamen" },
  { value: "kairouan", label: "Kairouan" },
  { value: "gabes", label: "Gabès" },
  { value: "bizerte", label: "Bizerte" },
  { value: "ariana", label: "Ariana" },
  { value: "gafsa", label: "Gafsa" },
  { value: "la-marsa", label: "La Marsa" },
  { value: "medenine", label: "Medenine" },
  { value: "sidi-bouzid", label: "Sidi Bouzid" },
  { value: "kasserine", label: "Kasserine" },
  { value: "ben-arous", label: "Ben Arous" },
  { value: "monastir", label: "Monastir" },
  { value: "nabeul", label: "Nabeul" },
  { value: "zarzis", label: "Zarzis" },
  { value: "mahdia", label: "Mahdia" },
  { value: "jendouba", label: "Jendouba" },
  { value: "el-kef", label: "El Kef" },
  { value: "siliana", label: "Siliana" },
  { value: "beja", label: "Beja" },
  { value: "tozeur", label: "Tozeur" },
  { value: "douz", label: "Douz" },
  { value: "tataouine", label: "Tataouine" },
  { value: "matmata", label: "Matmata" },
  { value: "kebili", label: "Kebili" },
  { value: "el-hamma", label: "El Hamma" },
  { value: "zaghouan", label: "Zaghouan" },
  { value: "hammamet", label: "Hammamet" },
  { value: "korba", label: "Korba" },
  { value: "menzel-temime", label: "Menzel Temime" },
  { value: "moknine", label: "Moknine" },
  { value: "bekalta", label: "Bekalta" },
  { value: "sakiet-ezzit", label: "Sakiet Ezzit" },
  { value: "sakiet-eddaier", label: "Sakiet Eddaïer" },
  { value: "beni-khalled", label: "Beni Khalled" },
  { value: "hammam-lif", label: "Hammam-Lif" },
  { value: "rades", label: "Radès" },
  { value: "mornag", label: "Mornag" },
  { value: "menzel-bourguiba", label: "Menzel Bourguiba" },
  { value: "el-alia", label: "El Alia" },
  { value: "grombalia", label: "Grombalia" },
  { value: "djerba", label: "Djerba" },
  { value: "houmt-souk", label: "Houmt Souk" },
  { value: "midoun", label: "Midoun" },
];
